### ISSUE TITLE
questions about the output dims of heatmaps

### ISSUE THREAD

**Issue by zhhtu** [princeton-vl/CornerNet-Lite#102]
hi ,first, thanks for the repo, it's quite helpful.
I've got some questions about the CornerNet implementation of the codes here. 

According to the paper, the output should of heatmaps should have dims like [Batch, Class. 128 128] for ONE keypoint (tl_heats or br_heats), but the implementation has TWO this maps concat as a LIST, while in the focal loss in Losses.py, this two maps' loss sums up together, could I ask, what's the meaning of the second maps?
Also, another question is about the output size of "tags" & "offs", why not just output same size maps as the labels of "tags" & "offs" directly instead of "gathering" from the output maps with "tensor.gather" ? Would the "gathering" helps the performance of the model?
Thank you very much!

**Comment by heilaw** [comment]
1. Because we have intermediate supervision. During training, we use predictions from both hourglass modules to calculate the losses, following the common practice of training a stacked hourglass network. But, during inference, only the predictions from the last hourglass module are used.
2. We only calculate the tag and offset loss at the corner locations so I find this would make the loss implementation a little bit easier and cleaner. It's just a personal preference.

**Comment by zhhtu** [comment]
> 1. Because we have intermediate supervision. During training, we use predictions from both hourglass modules to calculate the losses, following the common practice of training a stacked hourglass network. But, during inference, only the predictions from the last hourglass module are used.
> 2. We only calculate the tag and offset loss at the corner locations so I find this would make the loss implementation a little bit easier and cleaner. It's just a personal preference.

Thank you for the reply, learnt lot from the code 😊
