### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by lucasjinreal** [princeton-vl/CornerNet-Lite#3]
![image](https://user-images.githubusercontent.com/21303438/56423313-12d93f80-62de-11e9-94e1-4855454b453d.png)

0.4s on video

**Comment by heilaw** [comment]
Which detector were you using? Can you provide more details about your hardware configuration and the images that you were using?

**Comment by lucasjinreal** [comment]
@heilaw  I am using CenterNet_Sacaed structure and my PC is GTX 1080 TI.

I just directly test in `demo.py` by change loading from video. ( I donn't know if opened cuda or not).

But even on CPU, 400ms is till very slow. Yolov3 can get 30-40ms on CUDA, 100ms on CPU.
why CenterNet so time cost anyway?

**Comment by lucasjinreal** [comment]
@heilaw  The video I am using is from MOT with size about 640x480

**Comment by heilaw** [comment]
Thanks for the information.

On our machine also with a 1080Ti, the average inference time of CornerNet-Saccade is 190ms on COCO. I tested CornerNet-Saccade on the video you were using and obtained inference time similar to that on COCO.

I think I need more information so that I can further look into this issue. Are you using Anaconda Python? What is the CUDA version on your machine? It would also be great if you can share your script. Have a nice weekend.

**Comment by lucasjinreal** [comment]
@heilaw  I shall post it tomorrow. But 190ms still very slow in terms of yolov3

**Comment by heilaw** [comment]
If you want a real time detector, you may want to checkout CornerNet-Squeeze instead of CornerNet-Saccade. The average inference time of CornerNet-Squeeze on COCO is 30ms on our machine with a 1080Ti and an Intel Core i7-7700k.

**Comment by lucasjinreal** [comment]
@heilaw  After test, the squeeze net can achieve a promising speed, but with some false detections when inference on a car highway video
